name: manage infra

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - uat
          - prod
      aws_region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'
        type: choice
        options:
          - us-east-1
          - us-east-2
      terraform_action:
        description: 'Terraform action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy
      source_branch:
        description: 'Branch of the source repo to checkout'
        required: true
        default: 'main'

jobs:
  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: ${{ inputs.aws_region }}
      ENVIRONMENT: ${{ inputs.environment }}
      TF_ACTION: ${{ inputs.terraform_action }}
    steps:
      - name: Checkout infrastructure repo
        uses: actions/checkout@v4

      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          repository: BheemrajRH/Operationautomation
          ref: ${{ inputs.source_branch }}
          token: ${{ secrets.GH_PAT }}
          path: tf-source

      - name: List files in source repo
        run: ls -la tf-source/terraform/env/${ENVIRONMENT}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Set AWS Role to Assume
        id: set-role
        run: |
          if [ "$ENVIRONMENT" = "prod" ]; then
            echo "role_arn=${AWS_ROLE_ROLE_PROD}" >> "$GITHUB_OUTPUT"
          else
            echo "role_arn=${AWS_ROLE_ROLE}" >> "$GITHUB_OUTPUT"
          fi
        env:
          AWS_ROLE_ROLE_PROD: ${{ secrets.AWS_ROLE_ROLE_PROD }}
          AWS_ROLE_ROLE: ${{ secrets.AWS_ROLE_ROLE }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ steps.set-role.outputs.role_arn }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform -chdir=tf-source/terraform/env/${ENVIRONMENT} init -backend-config="key=deposits/${ENVIRONMENT}.tfstate" -var="region=${AWS_REGION}" -input=false

      - name: Terraform Action
        run: |
          if [ "$TF_ACTION" = "plan" ]; then
            terraform -chdir=tf-source/terraform/env/${ENVIRONMENT} plan -var-file=${ENVIRONMENT}.tfvars -var="region=${AWS_REGION}" -input=false
          elif [ "$TF_ACTION" = "apply" ]; then
            terraform -chdir=tf-source/terraform/env/${ENVIRONMENT} apply -auto-approve -var-file=${ENVIRONMENT}.tfvars -var="region=${AWS_REGION}" -input=false
          elif [ "$TF_ACTION" = "destroy" ]; then
            terraform -chdir=tf-source/terraform/env/${ENVIRONMENT} destroy -auto-approve -var-file=${ENVIRONMENT}.tfvars -var="region=${AWS_REGION}" -input=false
          else
            echo "Unsupported action: $TF_ACTION"
            exit 1
